name: Deploy my lambda Function
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install libraries
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: create zip bundle
        run: |
          zip -r ${{ github.workspace }}/${{ github.sha }}.zip .
      - name: archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zip-bundle
          path: ${{ github.workspace }}/${{ github.sha }}.zip

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: zip-bundle
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
      - name: Upload to S3
        run: aws s3 cp "${{ github.workspace }}/${{ github.sha }}.zip" "s3://mauro-github-actions-bucket/${{ github.sha }}.zip"

  deploy:
    runs-on: ubuntu-latest
    needs: upload
    steps: 
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
      - name: Update Function code
        run: |
          aws lambda update-function-code \
            --function-name mauro-lambda-function \
            --s3-bucket mauro-github-actions-bucket \
            --s3-key ${{ github.sha }}.zip \
            --publish

## Add a new job for static code analysis
# Checkout the code to the runner
# Configure python on the runner
# Install the required libraries using flake8
# Run Lint checks on the code
#This job should run before the build job
# If the lint check fails, the job should fail
# If the lint check passes, the job should pass
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install linting libraries
        run: |
          cd function
          pip install flake8
      - name: run linting checks with flake8
        run: |
            # Select identifies which errors should cause the job to fail
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # The exit zero flag will show errors as warnings and not fail the run
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  





